### ISSUE TITLE
name 'logger' is not defined

### ISSUE THREAD

**Issue by nanshakov** [hikiko4ern/vk_dump#14]
[сохранение видео]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing
\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing
\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 299
, in download_video
    return download_external(v['player'], folder)
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 328
, in download_external
    'logger': logger,
NameError: name 'logger' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 143
6, in <module>
    menu()
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 125
3, in menu
    choice()
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 138
3, in settings_screen
    settings_screen()
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 135
6, in settings_screen
    menu()
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 125
3, in menu
    choice()
  File "C:\Users\User\Downloads\vk_dump-master\vk_dump-master\dump.py", line 892
, in dump_messages
    videos['items'], itertools.repeat(af)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing
\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\multiprocessing
\pool.py", line 657, in get
    raise self._value
NameError: name 'logger' is not defined

**Comment by nanshakov** [comment]
Было бы хорошо выпустить фикс до 15

**Comment by hikiko4ern** [comment]
@nanshakov, попробуй заменить dump.py на файл из [этого коммита](https://github.com/hikiko4ern/vk_dump/tree/b48dca8ffd39c6fdf162091d7af2dd1625d4d490).
Если не спасёт - опиши действия, которые привели к данной ошибке.
